name: Deploy Website

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:

  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Deploy to EC2
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ec2-user
      key: ${{ secrets.EC2_KEY }}
      port: 22
      script: |
        if [ ! -d "pine_website" ]; then
          git clone https://github.com/Patilrohit777/pine_website.git
        fi

        cd pine_website

        git pull origin main

        docker stop sip-calculator || true
        docker rm sip-calculator || true

        docker build -t sip-calculator .

        docker run -d -p 80:80 --name sip-calculator sip-calculator

